#!/usr/bin/env Rscript
source(here::here("R/utils.R"))
source(here::here("R/extraction.R"))

# === QUALITY ASSESSMENTS (ROB2 for RCTs, ROBINS-I for observational) ===

qa_rows <- list(
  # --- Janse 2018: Web-based CBT RCT (n=240, 3-arm) ---
  # ROB2 domains: randomisation, deviations, missing_data, outcome_measurement, selection_reporting, overall
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="randomisation", judgement="low",
    rationale="Computer-generated randomisation with stratification by CFS criteria; allocation concealed via web-based system",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="deviations", judgement="some concerns",
    rationale="Participants not blinded to iCBT vs waiting list; therapists aware of condition. However, iCBT delivery is standardised",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="missing_data", judgement="low",
    rationale="ITT analysis; 89% completed T1 assessment across groups; multiple imputation used",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="outcome_measurement", judgement="some concerns",
    rationale="Primary outcome (CIS fatigue) is self-report in an unblinded trial; susceptible to expectation bias",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="selection_reporting", judgement="low",
    rationale="Pre-registered (NTR4013); all pre-specified outcomes reported",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="janse2018", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="overall", judgement="some concerns",
    rationale="Well-designed RCT with adequate randomisation and low attrition, but open-label with self-report outcomes",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),

  # --- Li 2017: TEAS RCT (n=89, sham-controlled) ---
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="randomisation", judgement="low",
    rationale="Randomised allocation described; 89 patients randomised to active (n=46) vs sham (n=43)",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="deviations", judgement="low",
    rationale="Sham-controlled with identical electrode placement; only current intensity differed (14 mA vs 1 mA); adequate blinding",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="missing_data", judgement="some concerns",
    rationale="No dropout information reported; unclear if ITT analysis used",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="outcome_measurement", judgement="low",
    rationale="FSS and SPHERE are validated self-report instruments; sham-controlled design mitigates expectation bias",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="selection_reporting", judgement="some concerns",
    rationale="No trial registration mentioned; Chinese journal publication; pre-specification of outcomes unclear",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="li2017", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="overall", judgement="some concerns",
    rationale="Good sham control but missing data handling unclear and no registration",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),

  # --- Bourke 2014: PACE trial pain secondary analysis (n=641) ---
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="randomisation", judgement="low",
    rationale="PACE trial: computer-generated randomisation with stratified allocation; large multicentre trial",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="deviations", judgement="high",
    rationale="Open-label design; participants and therapists aware of allocation; 4 active arms not blinded",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="missing_data", judgement="low",
    rationale="82% completed 52-week follow-up; multiple imputation used; sensitivity analyses conducted",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="outcome_measurement", judgement="high",
    rationale="Pain frequency is self-reported in an unblinded trial; CDC symptom criteria used as outcome measure; susceptible to reporting bias",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="selection_reporting", judgement="some concerns",
    rationale="Pain was a secondary/post-hoc analysis of PACE; primary outcomes were fatigue and function, not pain",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="bourke2014", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="overall", judgement="high",
    rationale="Large trial but open-label with self-report pain outcomes and post-hoc analysis; effect sizes small (d=0.24-0.31)",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),

  # --- Ali 2017: Guided self-help cohort (n=294) ---
  # ROBINS-I: confounding, selection, classification, deviations, missing_data, outcome_measurement, reporting, overall
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="confounding", judgement="serious",
    rationale="Single-arm cohort with no control group; improvement could reflect natural recovery, regression to mean, or expectation",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="selection", judgement="moderate",
    rationale="Consecutive referrals to specialist CFS clinic; some selection bias from referral pathway",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="missing_data", judgement="moderate",
    rationale="Multilevel models handle some missing data but dropout rates not clearly reported",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="outcome_measurement", judgement="serious",
    rationale="All outcomes self-report (SF-36, Chalder, WSAS) in uncontrolled design",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="reporting", judgement="low",
    rationale="Standard outcomes reported consistently across timepoints",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="ali2017", search_topic="treatment_cbt_psych", rob_tool="ROBINS-I",
    domain_name="overall", judgement="serious",
    rationale="No control group; self-report outcomes only; cannot distinguish treatment effect from natural history",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),

  # --- Vos-Vromans 2016: Secondary analysis of FatiGo RCT (n=122) ---
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="randomisation", judgement="low",
    rationale="Secondary analysis of FatiGo RCT; adequate randomisation in parent trial",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="deviations", judgement="high",
    rationale="Open-label; CBT vs MRT clearly distinguishable to participants and therapists",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="missing_data", judgement="some concerns",
    rationale="122 of original trial included with CEQ data; 9 missing CEQ forms",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="outcome_measurement", judgement="some concerns",
    rationale="CIS fatigue and SF-36 are self-report; unblinded design",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="selection_reporting", judgement="low",
    rationale="Pre-specified analysis plan; CEQ measured at standard timepoint",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="vos-vromans2016", search_topic="treatment_cbt_psych", rob_tool="rob2",
    domain_name="overall", judgement="some concerns",
    rationale="Parent trial well-designed but open-label; expectancy analysis is secondary/exploratory",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),

  # --- Cheshire 2020: Qualitative study ---
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="clear_aims", judgement="yes",
    rationale="Clear aim to explore patient experiences of GES in improved and deteriorated groups",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="methodology", judgement="yes",
    rationale="Qualitative methods appropriate for exploring subjective experiences",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="design", judgement="yes",
    rationale="Semi-structured interviews with constant comparison; purposive sampling of improved and deteriorated participants",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="analysis", judgement="yes",
    rationale="Thematic analysis with constant comparison method described adequately",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="findings", judgement="yes",
    rationale="Findings clearly stated with supporting quotes; indeterminate phase identified as novel finding",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE),
  data.frame(study_id="cheshire2020", search_topic="treatment_cbt_psych", rob_tool="casp_qualitative",
    domain_name="value", judgement="yes",
    rationale="Valuable contribution identifying barriers and facilitators to GES, including PEM-related deterioration",
    llm_model="manual-claude-assessment", stringsAsFactors=FALSE)
)

qa_df <- do.call(rbind, qa_rows)
write_quality_data(qa_df)
cat(sprintf("Wrote %d quality assessment rows for %d studies\n", nrow(qa_df), length(unique(qa_df$study_id))))

# === GRADE ASSESSMENTS ===
# For the newly extracted outcomes that contribute to domain-level evidence

grade_rows <- list(
  data.frame(
    outcome="Pre-2020 CBT: Fatigue (iCBT)", domain="treatment_cbt_psych",
    n_studies=1L, n_participants=240L,
    effect_estimate="d=0.58-0.60 (CIS fatigue, iCBT vs waiting list)",
    starting_certainty="high",
    downgrade_risk_of_bias=-1L, downgrade_inconsistency=0L,
    downgrade_indirectness=0L, downgrade_imprecision=-1L,
    downgrade_publication_bias=0L,
    upgrade_large_effect=0L, upgrade_dose_response=0L, upgrade_residual_confounding=0L,
    certainty="low",
    certainty_rationale="Starting HIGH (RCT). Downgraded -1 risk of bias: open-label with self-report CIS fatigue outcome. Downgraded -1 imprecision: single trial, though n=240 is adequate. Effect size moderate (d=0.58-0.60). 36-43% reached normal fatigue range vs 15% WL (NNT 3.6-4.7).",
    llm_model="manual-claude-assessment", study_id="janse2018", search_topic=NA_character_,
    stringsAsFactors=FALSE),
  data.frame(
    outcome="Pre-2020 TEAS: Fatigue", domain="treatment_cbt_psych",
    n_studies=1L, n_participants=89L,
    effect_estimate="FSS and SPHERE significantly reduced (p<0.001)",
    starting_certainty="high",
    downgrade_risk_of_bias=0L, downgrade_inconsistency=0L,
    downgrade_indirectness=-1L, downgrade_imprecision=-1L,
    downgrade_publication_bias=0L,
    upgrade_large_effect=0L, upgrade_dose_response=0L, upgrade_residual_confounding=0L,
    certainty="low",
    certainty_rationale="Starting HIGH (sham-controlled RCT with adequate blinding). No downgrade for RoB (sham control). Downgraded -1 indirectness: CFS diagnosed by Chinese criteria, may not map directly to Fukuda/ICC. Downgraded -1 imprecision: single small trial (n=89).",
    llm_model="manual-claude-assessment", study_id="li2017", search_topic=NA_character_,
    stringsAsFactors=FALSE),
  data.frame(
    outcome="Pre-2020 PACE: Pain outcomes", domain="treatment_cbt_psych",
    n_studies=1L, n_participants=641L,
    effect_estimate="CBT/GET vs SMC: d=0.24-0.31 for muscle/joint pain",
    starting_certainty="high",
    downgrade_risk_of_bias=-2L, downgrade_inconsistency=0L,
    downgrade_indirectness=0L, downgrade_imprecision=0L,
    downgrade_publication_bias=0L,
    upgrade_large_effect=0L, upgrade_dose_response=0L, upgrade_residual_confounding=0L,
    certainty="very low",
    certainty_rationale="Starting HIGH (RCT). Downgraded -2 risk of bias: open-label with self-report pain frequency; secondary/post-hoc analysis; PACE trial has documented methodological concerns including outcome switching. Effect sizes small (d=0.24-0.31). No downgrade imprecision (n=641). Treatment effects independent of fatigue change, but clinical significance uncertain.",
    llm_model="manual-claude-assessment", study_id="bourke2014", search_topic=NA_character_,
    stringsAsFactors=FALSE),
  data.frame(
    outcome="Pre-2020 Self-help: Physical function", domain="treatment_cbt_psych",
    n_studies=1L, n_participants=294L,
    effect_estimate="+2.7 SF-36 points during self-help (p=.044)",
    starting_certainty="low",
    downgrade_risk_of_bias=-1L, downgrade_inconsistency=0L,
    downgrade_indirectness=0L, downgrade_imprecision=-1L,
    downgrade_publication_bias=0L,
    upgrade_large_effect=0L, upgrade_dose_response=0L, upgrade_residual_confounding=0L,
    certainty="very low",
    certainty_rationale="Starting LOW (observational cohort, no control group). Downgraded -1 risk of bias: no control for natural recovery or regression to mean. Downgraded -1 imprecision: borderline significant (p=.044), CI nearly includes zero. Improvement small (2.7 points on SF-36) and may not be clinically meaningful.",
    llm_model="manual-claude-assessment", study_id="ali2017", search_topic=NA_character_,
    stringsAsFactors=FALSE),
  data.frame(
    outcome="Pre-2020 Treatment expectations moderate MRT outcomes", domain="treatment_cbt_psych",
    n_studies=1L, n_participants=122L,
    effect_estimate="Expectancy B=-1.52 (p=.001) for MRT fatigue; NS for CBT",
    starting_certainty="high",
    downgrade_risk_of_bias=-1L, downgrade_inconsistency=0L,
    downgrade_indirectness=-1L, downgrade_imprecision=-1L,
    downgrade_publication_bias=0L,
    upgrade_large_effect=0L, upgrade_dose_response=0L, upgrade_residual_confounding=0L,
    certainty="very low",
    certainty_rationale="Starting HIGH (secondary analysis of RCT). Downgraded -1 RoB: open-label, self-report outcomes; expectancy measured post-randomisation (potentially confounded by treatment experience). Downgraded -1 indirectness: tests moderator effect, not treatment effect per se. Downgraded -1 imprecision: single trial, modest sample (n=122).",
    llm_model="manual-claude-assessment", study_id="vos-vromans2016", search_topic=NA_character_,
    stringsAsFactors=FALSE)
)

grade_df <- do.call(rbind, grade_rows)
write_grade_data(grade_df)
cat(sprintf("Wrote %d GRADE assessments\n", nrow(grade_df)))
