#!/usr/bin/env Rscript
source(here::here("R/utils.R"))
source(here::here("R/extraction.R"))

rows <- list(
  list(study_id="ali2017", intervention_category="Guided Self-Help",
       outcome_domain="physical function", outcome_measure="SF-36 Physical Functioning",
       mean_intervention=NA, sd_intervention=NA, n_intervention=294L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=NA,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Pre-post cohort: +2.7 points (95% CI 0.1-5.3, p=.044) during self-help waiting phase"),
  list(study_id="ali2017", intervention_category="CBT",
       outcome_domain="fatigue", outcome_measure="Chalder Fatigue Scale",
       mean_intervention=NA, sd_intervention=NA, n_intervention=294L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=NA,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Pre-post cohort: -8.0 points (95% CI -6.9 to -9.1, p<.001) after CBT"),
  list(study_id="ali2017", intervention_category="CBT",
       outcome_domain="physical function", outcome_measure="SF-36 Physical Functioning",
       mean_intervention=NA, sd_intervention=NA, n_intervention=294L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=NA,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Pre-post cohort: +9.6 points (95% CI 6.9-12.4, p<.001) after CBT"),
  list(study_id="ali2017", intervention_category="CBT",
       outcome_domain="work and social", outcome_measure="WSAS",
       mean_intervention=NA, sd_intervention=NA, n_intervention=294L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=NA,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Pre-post cohort: -7.1 points (95% CI -6.0 to -8.3, p<.001) after CBT"),
  list(study_id="li2017", intervention_category="Acupuncture/TEAS",
       outcome_domain="fatigue", outcome_measure="Fatigue Severity Scale (FSS)",
       mean_intervention=NA, sd_intervention=NA, n_intervention=46L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=43L,
       dose="30 min/day, 5x/week, 4 weeks; intensity 14+/-2 mA",
       pem_assessed=FALSE, adverse_events_reported=TRUE,
       adverse_events_detail="No adverse reactions occurred",
       notes="TEAS vs sham: FSS significantly reduced (p<0.001 vs control)"),
  list(study_id="li2017", intervention_category="Acupuncture/TEAS",
       outcome_domain="symptoms (general)", outcome_measure="SPHERE",
       mean_intervention=NA, sd_intervention=NA, n_intervention=46L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=43L,
       dose="30 min/day, 5x/week, 4 weeks; intensity 14+/-2 mA",
       pem_assessed=FALSE, adverse_events_reported=TRUE,
       adverse_events_detail="No adverse reactions occurred",
       notes="TEAS vs sham: SPHERE significantly reduced (p<0.001 vs control)"),
  list(study_id="janse2018", intervention_category="CBT",
       outcome_domain="fatigue", outcome_measure="CIS Fatigue Severity",
       mean_intervention=36.3, sd_intervention=14.6, n_intervention=80L,
       mean_comparator=43.9, sd_comparator=10.5, n_comparator=80L,
       dose="Internet-based CBT with protocol-driven feedback; median 27 weeks",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="iCBT protocol vs WL: B=-8.3 (97.5% CI -12.7 to -3.9), p<.0001, d=0.58"),
  list(study_id="janse2018", intervention_category="CBT",
       outcome_domain="fatigue", outcome_measure="CIS Fatigue Severity",
       mean_intervention=37.0, sd_intervention=13.1, n_intervention=80L,
       mean_comparator=43.9, sd_comparator=10.5, n_comparator=80L,
       dose="Internet-based CBT with feedback on demand; median 27 weeks",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="iCBT on-demand vs WL: B=-7.2 (97.5% CI -11.3 to -3.1), p<.0001, d=0.60"),
  list(study_id="janse2018", intervention_category="CBT",
       outcome_domain="physical function", outcome_measure="SIP8",
       mean_intervention=867.8, sd_intervention=670.4, n_intervention=80L,
       mean_comparator=1322.5, sd_comparator=720.8, n_comparator=80L,
       dose="Internet-based CBT with protocol-driven feedback",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="iCBT protocol vs WL: B=-356.0 (95% CI -530 to -182), p<.0001, d=0.64"),
  list(study_id="janse2018", intervention_category="CBT",
       outcome_domain="physical function", outcome_measure="SF-36 Physical Functioning",
       mean_intervention=77.0, sd_intervention=21.3, n_intervention=80L,
       mean_comparator=70.8, sd_comparator=21.0, n_comparator=80L,
       dose="Internet-based CBT with feedback on demand",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="iCBT on-demand vs WL: p=.03, d=0.29"),
  list(study_id="janse2018", intervention_category="CBT",
       outcome_domain="depression", outcome_measure="SCL-90",
       mean_intervention=135.0, sd_intervention=36.4, n_intervention=80L,
       mean_comparator=154.8, sd_comparator=47.6, n_comparator=80L,
       dose="Internet-based CBT with protocol-driven feedback",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="iCBT protocol vs WL: B=-14.2 (95% CI -24.7 to -3.8), p=.008, d=0.47"),
  list(study_id="bourke2014", intervention_category="CBT",
       outcome_domain="pain", outcome_measure="CDC muscle pain frequency",
       mean_intervention=NA, sd_intervention=NA, n_intervention=161L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=160L,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="CBT vs SMC: mean diff 0.38, p=.02, d=0.25-0.31"),
  list(study_id="bourke2014", intervention_category="Graded Exercise Therapy",
       outcome_domain="pain", outcome_measure="CDC muscle pain frequency",
       mean_intervention=NA, sd_intervention=NA, n_intervention=160L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=160L,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="GET vs SMC: mean diff 0.42, p=.01, d=0.25-0.31"),
  list(study_id="bourke2014", intervention_category="CBT",
       outcome_domain="pain", outcome_measure="CDC joint pain frequency",
       mean_intervention=NA, sd_intervention=NA, n_intervention=161L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=159L,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="CBT vs APT: mean diff 0.35, p=.02, d=0.24-0.26"),
  list(study_id="bourke2014", intervention_category="Graded Exercise Therapy",
       outcome_domain="pain", outcome_measure="Fibromyalgia diagnosis",
       mean_intervention=NA, sd_intervention=NA, n_intervention=160L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=160L,
       dose=NA, pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="GET vs SMC: fibromyalgia 15% vs 27%, diff 12.3%, p=.01"),
  list(study_id="vos-vromans2016", intervention_category="Rehabilitation",
       outcome_domain="fatigue", outcome_measure="CIS Fatigue subscale",
       mean_intervention=NA, sd_intervention=NA, n_intervention=57L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=56L,
       dose="Multidisciplinary rehabilitation treatment (MRT)",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Expectancy predicts MRT fatigue outcome: B=-1.52 (95% CI -2.39 to -0.66, p=.001)"),
  list(study_id="vos-vromans2016", intervention_category="CBT",
       outcome_domain="fatigue", outcome_measure="CIS Fatigue subscale",
       mean_intervention=NA, sd_intervention=NA, n_intervention=56L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=NA,
       dose="CBT",
       pem_assessed=FALSE, adverse_events_reported=FALSE,
       adverse_events_detail=NA,
       notes="Expectancy did not predict CBT fatigue outcome: B=-0.47, p=.29"),
  list(study_id="cheshire2020", intervention_category="Graded Exercise Therapy",
       outcome_domain="symptoms (general)", outcome_measure="Qualitative themes",
       mean_intervention=NA, sd_intervention=NA, n_intervention=9L,
       mean_comparator=NA, sd_comparator=NA, n_comparator=10L,
       dose="Guided graded Exercise Self-help booklet",
       pem_assessed=TRUE, adverse_events_reported=TRUE,
       adverse_events_detail="Deteriorated group reported symptom exacerbation after GES",
       notes="Qualitative: 9 improved vs 10 deteriorated. Longer illness and PEM predicted deterioration")
)

df <- do.call(rbind, lapply(rows, as.data.frame, stringsAsFactors = FALSE))
df$search_topic <- "treatment_cbt_psych"
df$llm_model <- "manual-claude-extraction"

write_extracted_data(df, "treatment_cbt_psych")
cat(sprintf("Wrote %d effect sizes for %d studies\n", nrow(df), length(unique(df$study_id))))

db <- read_study_database()
for (sid in unique(df$study_id)) {
  idx <- which(db$study_id == sid & db$llm_model == "manual-claude-screening" & !is.na(db$llm_model))
  if (length(idx) > 0) db$data_extracted[idx[1]] <- TRUE
}
for (sid in c("xie2019", "goldsmith2011", "goudsmit2012", "antcliff2013", "krzeczkowska2015")) {
  idx <- which(db$study_id == sid & db$llm_model == "manual-claude-screening" & !is.na(db$llm_model))
  if (length(idx) > 0) {
    db$data_extracted[idx[1]] <- TRUE
    db$notes[idx[1]] <- switch(sid,
      xie2019 = "Protocol only, no results data",
      goldsmith2011 = "Conference abstract, methods paper only",
      goudsmit2012 = "Consensus review, no quantitative treatment data",
      antcliff2013 = "Questionnaire development (Delphi), no treatment outcomes",
      krzeczkowska2015 = "Cross-sectional, no intervention"
    )
  }
}
write_study_database(db)

new <- db[db$llm_model == "manual-claude-screening" & !is.na(db$llm_model) & db$llm_relevant %in% TRUE, ]
cat(sprintf("Extraction status: %d/%d marked as extracted\n", sum(new$data_extracted %in% TRUE), nrow(new)))
